### ISSUE TITLE
what is the definition for noncoding part when making hexamer table?

### ISSUE THREAD

**Issue by Shuixin-Li** [liguowang/cpat#10]
Dear author:
I am going to create custom hexamer table
```
  -c CODING_FILE, --cod=CODING_FILE
                        Coding sequence (must be CDS without UTR, i.e.
                        from start coden to stop coden) in fasta format
  -n NONCODING_FILE, --noncod=NONCODING_FILE
                        Noncoding sequences in fasta format
```
I've understand the coding file only wants CDS part with start coden and stop coden included (in other words, ORF+stop codon), but what is the definition for noncoding part? 

I've checked the biotype defined by ensembl
```
Long non-coding RNA (lncRNA): A non-coding gene/transcript >200bp in length
3' overlapping ncRNA: Transcripts where ditag and/or published experimental data strongly supports the existence of long (>200bp) non-coding transcripts that overlap the 3'UTR of a protein-coding locus on the same strand.
Antisense: Transcripts that overlap the genomic span (i.e. exon or introns) of a protein-coding locus on the opposite strand.
Macro lncRNA: Unspliced lncRNAs that are several kb in size.
Non coding: Transcripts which are known from the literature to not be protein coding.
Retained intron: An alternatively spliced transcript believed to contain intronic sequence relative to other, coding, transcripts of the same gene.
Sense intronic: A long non-coding transcript in introns of a coding gene that does not overlap any exons.
Sense overlapping: A long non-coding transcript that contains a coding gene in its intron on the same strand.
lincRNA (long intergenic ncRNA): Transcripts that are long intergenic non-coding RNA locus with a length >200bp. Requires lack of coding potential and may not be conserved between species.
ncRNA: A non-coding gene.
miRNA: A small RNA (~22bp) that silences the expression of target mRNA.
miscRNA: Miscellaneous RNA. A non-coding RNA that cannot be classified.
piRNA: An RNA that interacts with piwi proteins involved in genetic silencing.
rRNA: The RNA component of a ribosome.
siRNA: A small RNA (20-25bp) that silences the expression of target mRNA through the RNAi pathway.
snRNA: Small RNA molecules that are found in the cell nucleus and are involved in the processing of pre messenger RNAs
snoRNA: Small RNA molecules that are found in the cell nucleolus and are involved in the post-transcriptional modification of other RNAs.
tRNA: A transfer RNA, which acts as an adaptor molecule for translation of mRNA.
vaultRNA: Short non coding RNA genes that form part of the vault ribonucleoprotein complex.
```

there are so many types and I have no idea which type should be included. 

Thank you so much!! @liguowang

**Comment by liguowang** [comment]
It simply means the entire sequence of noncoding RNA. We have some test files available at https://sourceforge.net/projects/rna-cpat/files/test_files/On Apr 26, 2024, at 3:23 AM, Shuixin-Li ***@***.***> wrote:﻿
Dear author:
I am going to create custom hexamer table
  -c CODING_FILE, --cod=CODING_FILE
                        Coding sequence (must be CDS without UTR, i.e.
                        from start coden to stop coden) in fasta format
  -n NONCODING_FILE, --noncod=NONCODING_FILE
                        Noncoding sequences in fasta format

I've understand the coding file only wants CDS part with start coden and stop coden included (in other words, ORF+stop codon), but what is the definition for noncoding part?
I've checked the biotype defined by ensembl
Long non-coding RNA (lncRNA): A non-coding gene/transcript >200bp in length
3' overlapping ncRNA: Transcripts where ditag and/or published experimental data strongly supports the existence of long (>200bp) non-coding transcripts that overlap the 3'UTR of a protein-coding locus on the same strand.
Antisense: Transcripts that overlap the genomic span (i.e. exon or introns) of a protein-coding locus on the opposite strand.
Macro lncRNA: Unspliced lncRNAs that are several kb in size.
Non coding: Transcripts which are known from the literature to not be protein coding.
Retained intron: An alternatively spliced transcript believed to contain intronic sequence relative to other, coding, transcripts of the same gene.
Sense intronic: A long non-coding transcript in introns of a coding gene that does not overlap any exons.
Sense overlapping: A long non-coding transcript that contains a coding gene in its intron on the same strand.
lincRNA (long intergenic ncRNA): Transcripts that are long intergenic non-coding RNA locus with a length >200bp. Requires lack of coding potential and may not be conserved between species.
ncRNA: A non-coding gene.
miRNA: A small RNA (~22bp) that silences the expression of target mRNA.
miscRNA: Miscellaneous RNA. A non-coding RNA that cannot be classified.
piRNA: An RNA that interacts with piwi proteins involved in genetic silencing.
rRNA: The RNA component of a ribosome.
siRNA: A small RNA (20-25bp) that silences the expression of target mRNA through the RNAi pathway.
snRNA: Small RNA molecules that are found in the cell nucleus and are involved in the processing of pre messenger RNAs
snoRNA: Small RNA molecules that are found in the cell nucleolus and are involved in the post-transcriptional modification of other RNAs.
tRNA: A transfer RNA, which acts as an adaptor molecule for translation of mRNA.
vaultRNA: Short non coding RNA genes that form part of the vault ribonucleoprotein complex.

there are so many types and I have no idea which type should be included.
Thank you so much!! @liguowang

**Comment by Shuixin-Li** [comment]
Than you ,can I say all the regions outside CDS  (in rat genome) are the general noncoding part that you referred to?  @liguowang

**Comment by liguowang** [comment]
We used the moncodong RNAs identified previously. Not  the noncoding part of coding RNAs such as UTR ( this may also work, but not sure about the performance of the model)On Apr 26, 2024, at 7:05 AM, Shuixin-Li ***@***.***> wrote:﻿
Than you ,can I say all the regions outside CDS  (in rat genome) are the general noncoding part that you referred to?  @liguowang

**Comment by Shuixin-Li** [comment]
Thank you so much, I understand it now! Really thank you for your help!
